"""
Tests for CLI entry point (__main__.py).

Generated By: Claude Code (Claude Sonnet 4.5)
"""

import unittest
from io import StringIO
from unittest.mock import patch

from ap_copy_master_to_blink.__main__ import EXIT_ERROR, EXIT_SUCCESS, main


class TestMainCLI(unittest.TestCase):
    """Tests for main() CLI entry point."""

    def setUp(self):
        """Set up test fixtures."""
        self.mock_stats_success = {
            "frame_count": 100,
            "target_count": 2,
            "date_count": 3,
            "filter_count": 4,
            "biases_needed": 0,
            "biases_present": 0,
            "darks_needed": 5,
            "darks_present": 5,
            "flats_needed": 3,
            "flats_present": 3,
        }
        self.mock_stats_missing = {
            "frame_count": 100,
            "target_count": 2,
            "date_count": 3,
            "filter_count": 4,
            "biases_needed": 0,
            "biases_present": 0,
            "darks_needed": 5,
            "darks_present": 3,
            "flats_needed": 3,
            "flats_present": 2,
        }

    @patch("ap_copy_master_to_blink.__main__.process_blink_directory")
    @patch("ap_copy_master_to_blink.__main__.validate_directories")
    @patch("sys.argv", ["ap-copy-master-to-blink", "/tmp/lib", "/tmp/blink"])
    def test_successful_execution(self, mock_validate, mock_process):
        """Test successful execution with minimal args."""
        mock_validate.return_value = (True, None)
        mock_process.return_value = self.mock_stats_success

        result = main()

        self.assertEqual(result, EXIT_SUCCESS)
        mock_process.assert_called_once()

    @patch("ap_copy_master_to_blink.__main__.process_blink_directory")
    @patch("ap_copy_master_to_blink.__main__.validate_directories")
    @patch(
        "sys.argv", ["ap-copy-master-to-blink", "/tmp/lib", "/tmp/blink", "--dryrun"]
    )
    def test_dryrun_flag(self, mock_validate, mock_process):
        """Test execution with --dryrun flag."""
        mock_validate.return_value = (True, None)
        mock_process.return_value = self.mock_stats_success

        result = main()

        self.assertEqual(result, EXIT_SUCCESS)
        # Verify dry_run=True was passed
        call_args = mock_process.call_args
        self.assertTrue(call_args.kwargs["dry_run"])

    @patch("ap_copy_master_to_blink.__main__.process_blink_directory")
    @patch("ap_copy_master_to_blink.__main__.validate_directories")
    @patch("sys.argv", ["ap-copy-master-to-blink", "/tmp/lib", "/tmp/blink", "--quiet"])
    def test_quiet_flag(self, mock_validate, mock_process):
        """Test execution with --quiet flag."""
        mock_validate.return_value = (True, None)
        mock_process.return_value = self.mock_stats_success

        result = main()

        self.assertEqual(result, EXIT_SUCCESS)
        # Verify quiet=True was passed
        call_args = mock_process.call_args
        self.assertTrue(call_args.kwargs["quiet"])

    @patch("ap_copy_master_to_blink.__main__.process_blink_directory")
    @patch("ap_copy_master_to_blink.__main__.validate_directories")
    @patch("sys.argv", ["ap-copy-master-to-blink", "/tmp/lib", "/tmp/blink", "--debug"])
    def test_debug_flag(self, mock_validate, mock_process):
        """Test execution with --debug flag."""
        mock_validate.return_value = (True, None)
        mock_process.return_value = self.mock_stats_success

        result = main()

        self.assertEqual(result, EXIT_SUCCESS)

    @patch("ap_copy_master_to_blink.__main__.process_blink_directory")
    @patch("ap_copy_master_to_blink.__main__.validate_directories")
    @patch(
        "sys.argv",
        ["ap-copy-master-to-blink", "/tmp/lib", "/tmp/blink", "--scale-dark"],
    )
    def test_scale_darks_flag(self, mock_validate, mock_process):
        """Test execution with --scale-dark flag."""
        mock_validate.return_value = (True, None)
        mock_process.return_value = self.mock_stats_success

        result = main()

        self.assertEqual(result, EXIT_SUCCESS)
        # Verify scale_darks=True was passed
        call_args = mock_process.call_args
        self.assertTrue(call_args.kwargs["scale_darks"])

    @patch("ap_copy_master_to_blink.__main__.process_blink_directory")
    @patch("ap_copy_master_to_blink.__main__.validate_directories")
    @patch(
        "sys.argv",
        [
            "ap-copy-master-to-blink",
            "/tmp/lib",
            "/tmp/blink",
            "--flat-state",
            "/tmp/state.yaml",
        ],
    )
    def test_flat_state_flag(self, mock_validate, mock_process):
        """Test execution with --flat-state flag."""
        mock_validate.return_value = (True, None)
        mock_process.return_value = self.mock_stats_success

        result = main()

        self.assertEqual(result, EXIT_SUCCESS)
        # Verify flat_state_path was passed
        call_args = mock_process.call_args
        self.assertIsNotNone(call_args.kwargs["flat_state_path"])
        flat_state = str(call_args.kwargs["flat_state_path"])
        self.assertTrue(flat_state.endswith("state.yaml"))

    @patch("ap_copy_master_to_blink.__main__.process_blink_directory")
    @patch("ap_copy_master_to_blink.__main__.validate_directories")
    @patch(
        "sys.argv",
        [
            "ap-copy-master-to-blink",
            "/tmp/lib",
            "/tmp/blink",
            "--flat-state",
            "/tmp/state.yaml",
            "--picker-limit",
            "10",
        ],
    )
    def test_picker_limit_flag(self, mock_validate, mock_process):
        """Test execution with --picker-limit flag."""
        mock_validate.return_value = (True, None)
        mock_process.return_value = self.mock_stats_success

        result = main()

        self.assertEqual(result, EXIT_SUCCESS)
        # Verify picker_limit was passed
        call_args = mock_process.call_args
        self.assertEqual(call_args.kwargs["picker_limit"], 10)

    @patch("ap_copy_master_to_blink.__main__.validate_directories")
    @patch("sys.argv", ["ap-copy-master-to-blink", "/tmp/lib", "/tmp/blink"])
    @patch("sys.stderr", new_callable=StringIO)
    def test_invalid_directories(self, mock_stderr, mock_validate):
        """Test error handling for invalid directories."""
        mock_validate.return_value = (False, "Library directory does not exist")

        result = main()

        self.assertEqual(result, EXIT_ERROR)
        error_output = mock_stderr.getvalue()
        self.assertIn("Library directory does not exist", error_output)

    @patch("ap_copy_master_to_blink.__main__.process_blink_directory")
    @patch("ap_copy_master_to_blink.__main__.validate_directories")
    @patch("sys.argv", ["ap-copy-master-to-blink", "/tmp/lib", "/tmp/blink"])
    def test_missing_darks_returns_error(self, mock_validate, mock_process):
        """Test exit code when darks are missing."""
        mock_validate.return_value = (True, None)
        mock_process.return_value = self.mock_stats_missing

        result = main()

        self.assertEqual(result, EXIT_ERROR)

    @patch("ap_copy_master_to_blink.__main__.process_blink_directory")
    @patch("ap_copy_master_to_blink.__main__.validate_directories")
    @patch("sys.argv", ["ap-copy-master-to-blink", "/tmp/lib", "/tmp/blink", "--quiet"])
    def test_missing_darks_quiet_mode(self, mock_validate, mock_process):
        """Test quiet mode with missing darks."""
        mock_validate.return_value = (True, None)
        mock_process.return_value = self.mock_stats_missing

        result = main()

        self.assertEqual(result, EXIT_ERROR)

    @patch("ap_copy_master_to_blink.__main__.process_blink_directory")
    @patch("ap_copy_master_to_blink.__main__.validate_directories")
    @patch(
        "sys.argv",
        [
            "ap-copy-master-to-blink",
            "/tmp/lib",
            "/tmp/blink",
            "--dryrun",
            "--quiet",
            "--debug",
        ],
    )
    def test_multiple_flags_combined(self, mock_validate, mock_process):
        """Test execution with multiple flags combined."""
        mock_validate.return_value = (True, None)
        mock_process.return_value = self.mock_stats_success

        result = main()

        self.assertEqual(result, EXIT_SUCCESS)
        call_args = mock_process.call_args
        self.assertTrue(call_args.kwargs["dry_run"])
        self.assertTrue(call_args.kwargs["quiet"])

    @patch("ap_copy_master_to_blink.__main__.process_blink_directory")
    @patch("ap_copy_master_to_blink.__main__.validate_directories")
    @patch("sys.argv", ["ap-copy-master-to-blink", "/tmp/lib", "/tmp/blink"])
    def test_all_masters_present(self, mock_validate, mock_process):
        """Test successful execution when all masters are present."""
        mock_validate.return_value = (True, None)
        mock_process.return_value = {
            "frame_count": 50,
            "target_count": 1,
            "date_count": 1,
            "filter_count": 1,
            "biases_needed": 0,
            "biases_present": 0,
            "darks_needed": 0,
            "darks_present": 0,
            "flats_needed": 0,
            "flats_present": 0,
        }

        result = main()

        self.assertEqual(result, EXIT_SUCCESS)

    @patch("ap_copy_master_to_blink.__main__.process_blink_directory")
    @patch("ap_copy_master_to_blink.__main__.validate_directories")
    @patch("sys.argv", ["ap-copy-master-to-blink", "/tmp/lib", "/tmp/blink"])
    def test_only_flats_missing(self, mock_validate, mock_process):
        """Test exit code when only flats are missing."""
        mock_validate.return_value = (True, None)
        mock_process.return_value = {
            "frame_count": 100,
            "target_count": 2,
            "date_count": 3,
            "filter_count": 4,
            "biases_needed": 0,
            "biases_present": 0,
            "darks_needed": 5,
            "darks_present": 5,
            "flats_needed": 3,
            "flats_present": 1,
        }

        result = main()

        self.assertEqual(result, EXIT_ERROR)


if __name__ == "__main__":
    unittest.main()
