"""
Tests for configuration constants

Generated By: Claude Code (Claude Sonnet 4.5)
"""

import unittest

from ap_common.constants import (
    TYPE_MASTER_DARK,
    TYPE_MASTER_FLAT,
    TYPE_MASTER_BIAS,
    NORMALIZED_HEADER_CAMERA,
    NORMALIZED_HEADER_GAIN,
    NORMALIZED_HEADER_OFFSET,
    NORMALIZED_HEADER_SETTEMP,
    NORMALIZED_HEADER_READOUTMODE,
    NORMALIZED_HEADER_EXPOSURESECONDS,
    NORMALIZED_HEADER_DATE,
    NORMALIZED_HEADER_FILTER,
)
from ap_copy_master_to_blink.config import (
    SUPPORTED_EXTENSIONS,
    DARK_MATCHING_KEYWORDS,
    FLAT_MATCHING_KEYWORDS,
    BIAS_MATCHING_KEYWORDS,
)


class TestConfig(unittest.TestCase):
    """Test configuration constants."""

    def test_supported_extensions(self):
        """Test supported file extensions."""
        self.assertIn(".fits", SUPPORTED_EXTENSIONS)
        self.assertIn(".xisf", SUPPORTED_EXTENSIONS)

    def test_master_types(self):
        """Test master frame type constants."""
        self.assertEqual(TYPE_MASTER_DARK, "MASTER DARK")
        self.assertEqual(TYPE_MASTER_FLAT, "MASTER FLAT")
        self.assertEqual(TYPE_MASTER_BIAS, "MASTER BIAS")

    def test_dark_matching_keywords(self):
        """Test dark matching keywords include required fields."""
        self.assertIn(NORMALIZED_HEADER_CAMERA, DARK_MATCHING_KEYWORDS)
        self.assertIn(NORMALIZED_HEADER_GAIN, DARK_MATCHING_KEYWORDS)
        self.assertIn(NORMALIZED_HEADER_OFFSET, DARK_MATCHING_KEYWORDS)
        self.assertIn(NORMALIZED_HEADER_SETTEMP, DARK_MATCHING_KEYWORDS)
        self.assertIn(NORMALIZED_HEADER_READOUTMODE, DARK_MATCHING_KEYWORDS)
        self.assertIn(NORMALIZED_HEADER_EXPOSURESECONDS, DARK_MATCHING_KEYWORDS)

    def test_flat_matching_keywords(self):
        """Test flat matching keywords include required fields."""
        self.assertIn(NORMALIZED_HEADER_CAMERA, FLAT_MATCHING_KEYWORDS)
        self.assertIn(NORMALIZED_HEADER_GAIN, FLAT_MATCHING_KEYWORDS)
        self.assertIn(NORMALIZED_HEADER_OFFSET, FLAT_MATCHING_KEYWORDS)
        self.assertIn(NORMALIZED_HEADER_SETTEMP, FLAT_MATCHING_KEYWORDS)
        self.assertIn(NORMALIZED_HEADER_READOUTMODE, FLAT_MATCHING_KEYWORDS)
        self.assertIn(NORMALIZED_HEADER_FILTER, FLAT_MATCHING_KEYWORDS)
        self.assertIn(NORMALIZED_HEADER_DATE, FLAT_MATCHING_KEYWORDS)

    def test_bias_matching_keywords(self):
        """Test bias matching keywords include required fields."""
        self.assertIn(NORMALIZED_HEADER_CAMERA, BIAS_MATCHING_KEYWORDS)
        self.assertIn(NORMALIZED_HEADER_GAIN, BIAS_MATCHING_KEYWORDS)
        self.assertIn(NORMALIZED_HEADER_OFFSET, BIAS_MATCHING_KEYWORDS)
        self.assertIn(NORMALIZED_HEADER_SETTEMP, BIAS_MATCHING_KEYWORDS)
        self.assertIn(NORMALIZED_HEADER_READOUTMODE, BIAS_MATCHING_KEYWORDS)


if __name__ == "__main__":
    unittest.main()
