"""
CLI entry point for ap-copy-master-to-blink

Generated By: Claude Code (Claude Sonnet 4.5)
"""

import argparse
import sys
from pathlib import Path
from typing import Dict, Optional, Tuple

from ap_common import setup_logging, replace_env_vars, resolve_path

from .copy_masters import process_blink_directory


def validate_directories(
    library_dir: Path, blink_dir: Path
) -> Tuple[bool, Optional[str]]:
    """
    Validate that library and blink directories exist and are directories.

    Args:
        library_dir: Path to calibration library
        blink_dir: Path to blink directory tree

    Returns:
        Tuple of (is_valid, error_message)
        - is_valid: True if both directories are valid, False otherwise
        - error_message: Error message if invalid, None if valid
    """
    if not library_dir.exists():
        return False, f"Library directory does not exist: {library_dir}"

    if not library_dir.is_dir():
        return False, f"Library path is not a directory: {library_dir}"

    if not blink_dir.exists():
        return False, f"Blink directory does not exist: {blink_dir}"

    if not blink_dir.is_dir():
        return False, f"Blink path is not a directory: {blink_dir}"

    return True, None


def print_header(library_dir: Path, blink_dir: Path, dry_run: bool) -> None:
    """
    Print header before processing.

    Args:
        library_dir: Path to calibration library
        blink_dir: Path to blink directory tree
        dry_run: Whether this is a dry run
    """
    print(f"\n{'='*70}")
    print("ap-copy-master-to-blink")
    print(f"{'='*70}")
    print(f"Library: {library_dir}")
    print(f"Blink:   {blink_dir}")
    print(f"Dry-run: {dry_run}")
    print(f"{'='*70}\n")


def print_summary(stats: Dict[str, int]) -> None:
    """
    Print summary of processing results.

    Args:
        stats: Statistics dictionary from process_blink_directory
    """

    def plural(count: int, singular: str) -> str:
        """Format count with singular/plural form."""
        return f"{count} {singular}{'s' if count != 1 else ''}"

    def status_indicator(present: int, needed: int) -> str:
        """Return status indicator based on present vs needed."""
        return "ok" if present >= needed else "MISSING!"

    print(f"\n{'='*70}")
    print("Summary")
    print(f"{'='*70}")
    print(
        f"Frames: {stats['frame_count']} lights "
        f"({plural(stats['target_count'], 'target')}, "
        f"{plural(stats['date_count'], 'date')}, "
        f"{plural(stats['filter_count'], 'filter')})"
    )
    print(
        f"Biases: {stats['biases_present']} of {stats['biases_needed']} | "
        f"{status_indicator(stats['biases_present'], stats['biases_needed'])}"
    )
    print(
        f"Darks:  {stats['darks_present']} of {stats['darks_needed']} | "
        f"{status_indicator(stats['darks_present'], stats['darks_needed'])}"
    )
    print(
        f"Flats:  {stats['flats_present']} of {stats['flats_needed']} | "
        f"{status_indicator(stats['flats_present'], stats['flats_needed'])}"
    )
    print(f"{'='*70}\n")


def main() -> int:
    """Main CLI entry point."""
    parser = argparse.ArgumentParser(
        description="Copy master calibration frames from library to blink directories",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Basic usage
  python -m ap_copy_master_to_blink <library_dir> <blink_dir>

  # With dryrun
  python -m ap_copy_master_to_blink <library_dir> <blink_dir> --dryrun

  # With debug output
  python -m ap_copy_master_to_blink <library_dir> <blink_dir> --debug

  # Real example
  python -m ap_copy_master_to_blink \\
      "F:/Astrophotography/_Calibration Library" \\
      "F:/Astrophotography/RedCat51@f4.9+ASI2600MM/10_Blink"
        """,
    )

    parser.add_argument(
        "library_dir",
        type=str,
        help="Path to calibration library (supports env vars like $VAR or ${VAR})",
    )

    parser.add_argument(
        "blink_dir",
        type=str,
        help="Path to blink directory tree (supports env vars like $VAR or ${VAR})",
    )

    parser.add_argument(
        "--dryrun",
        action="store_true",
        help="Show what would be copied without actually copying files",
    )

    parser.add_argument(
        "--quiet",
        "-q",
        action="store_true",
        help="Suppress progress output",
    )

    parser.add_argument(
        "--debug",
        action="store_true",
        help="Enable debug logging",
    )

    parser.add_argument(
        "--allow-bias",
        action="store_true",
        help="Allow shorter darks with bias frames. "
        "Default: only exact exposure match darks are copied.",
    )

    args = parser.parse_args()

    # Setup logging
    setup_logging(name="ap_copy_master_to_blink", debug=args.debug, quiet=args.quiet)

    # Resolve paths (support environment variables)
    library_dir = Path(resolve_path(replace_env_vars(args.library_dir)))
    blink_dir = Path(resolve_path(replace_env_vars(args.blink_dir)))

    # Validate directories exist
    is_valid, error_message = validate_directories(library_dir, blink_dir)
    if not is_valid:
        print(f"Error: {error_message}", file=sys.stderr)
        return 1

    # Print header
    if not args.quiet:
        print_header(library_dir, blink_dir, args.dryrun)

    # Process blink directory
    stats = process_blink_directory(
        library_dir,
        blink_dir,
        dry_run=args.dryrun,
        quiet=args.quiet,
        allow_bias=args.allow_bias,
    )

    # Print summary
    if not args.quiet:
        print_summary(stats)

    # Return non-zero if any masters are missing
    darks_missing = stats["darks_needed"] - stats["darks_present"]
    flats_missing = stats["flats_needed"] - stats["flats_present"]

    if darks_missing > 0 or flats_missing > 0:
        if not args.quiet:
            print(
                "Warning: Some master frames are missing. Check logs above for details."
            )
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
