"""
Interactive picker for flat frame date selection.

Generated By: Claude Code (Claude Sonnet 4.5)
"""

import logging
from datetime import date
from typing import List, Optional, Tuple

import questionary

logger = logging.getLogger(__name__)

NONE_LABEL = "None of these (rig changed)"


def _day_diff_label(flat_date: date, light_date: date) -> str:
    """
    Generate a human-readable label for the day difference.

    Args:
        flat_date: The flat frame date
        light_date: The light frame date

    Returns:
        Label like "(3 days older)" or "(same day)"
    """
    diff = (flat_date - light_date).days

    if diff == 0:
        return "(same day)"
    elif diff < 0:
        days = abs(diff)
        plural = "s" if days != 1 else ""
        return f"({days} day{plural} older)"
    else:
        plural = "s" if diff != 1 else ""
        return f"({diff} day{plural} newer)"


def build_picker_items(
    light_date: date,
    older_dates: List[date],
    newer_dates: List[date],
    picker_limit: int,
) -> Tuple[List[str], List[Optional[date]], int, Optional[str], Optional[str]]:
    """
    Build the list of display items and corresponding date values.

    Args:
        light_date: The light frame date
        older_dates: Older candidate dates, sorted ascending (oldest first)
        newer_dates: Newer candidate dates, sorted ascending (oldest first)
        picker_limit: Max older/newer dates to show

    Returns:
        Tuple of:
        - display_lines: List of display strings for each selectable item
        - date_values: List of date objects (or None for the "none" option)
        - none_index: Index of the "None of these" option
        - older_overflow_msg: Message about hidden older dates, or None
        - newer_overflow_msg: Message about hidden newer dates, or None
    """
    display_lines: List[str] = []
    date_values: List[Optional[date]] = []

    # Older dates: show most recent N (tail of sorted list)
    older_overflow_msg = None
    if len(older_dates) > picker_limit:
        hidden = len(older_dates) - picker_limit
        older_overflow_msg = f"... {hidden} more older flats not shown"
        visible_older = older_dates[-picker_limit:]
    else:
        visible_older = older_dates

    for d in visible_older:
        label = f"{d.isoformat()}  {_day_diff_label(d, light_date)}"
        display_lines.append(label)
        date_values.append(d)

    # "None" option
    none_index = len(display_lines)
    display_lines.append(NONE_LABEL)
    date_values.append(None)

    # Newer dates: show oldest N (head of sorted list)
    newer_overflow_msg = None
    if len(newer_dates) > picker_limit:
        hidden = len(newer_dates) - picker_limit
        newer_overflow_msg = f"... {hidden} more newer flats not shown"
        visible_newer = newer_dates[:picker_limit]
    else:
        visible_newer = newer_dates

    for d in visible_newer:
        label = f"{d.isoformat()}  {_day_diff_label(d, light_date)}"
        display_lines.append(label)
        date_values.append(d)

    return (
        display_lines,
        date_values,
        none_index,
        older_overflow_msg,
        newer_overflow_msg,
    )


def pick_flat_date(
    light_date_str: str,
    filter_name: str,
    older_dates: List[date],
    newer_dates: List[date],
    picker_limit: int = 5,
) -> Optional[date]:
    """
    Display interactive picker for flat frame date selection.

    Uses questionary for cross-platform interactive terminal menu.
    For non-interactive environments, use --quiet mode to skip picker.

    Args:
        light_date_str: Light frame date as string (YYYY-MM-DD)
        filter_name: Filter name for display
        older_dates: Older candidate dates, sorted ascending
        newer_dates: Newer candidate dates, sorted ascending
        picker_limit: Max older/newer dates to show

    Returns:
        Selected date, or None if user chose "None of these (rig changed)"

    Raises:
        Exception: If questionary fails (no TTY, etc.)
            Use --quiet mode for non-interactive environments.
    """
    light_date = date.fromisoformat(light_date_str)

    display_lines, date_values, none_index, older_msg, newer_msg = build_picker_items(
        light_date, older_dates, newer_dates, picker_limit
    )

    if not older_dates and not newer_dates:
        logger.debug("No candidate flat dates to display")
        return None

    header = f"No exact flat for {light_date_str} (filter: {filter_name})"

    # Build message with overflow warnings
    message_lines = [header]
    if older_msg:
        message_lines.append(f"  {older_msg}")
    if newer_msg:
        message_lines.append(f"  {newer_msg}")

    selected_item = questionary.select(
        "\n".join(message_lines),
        choices=display_lines,
        default=display_lines[none_index],
        use_shortcuts=False,
        use_arrow_keys=True,
    ).ask()

    # User cancelled (Ctrl+C)
    if selected_item is None:
        logger.info(f"User cancelled picker for {light_date_str}")
        return None

    # Find selected date
    selected_idx = display_lines.index(selected_item)
    selected_date = date_values[selected_idx]

    if selected_date is None:
        logger.info(
            f"User selected 'rig changed' for {light_date_str} "
            f"(filter: {filter_name})"
        )
    else:
        logger.info(
            f"User selected flat date {selected_date.isoformat()} "
            f"for {light_date_str} (filter: {filter_name})"
        )

    return selected_date
